GET http://chat.lcl:8081/api/v1/chats
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiZWI1ZmU3NDhmZjExN2JjMmQ0ZjdiYWQ2ODFiNjM4MWE0YjJlZmRjZTkyMWI4OWVlNTc2ZTEzYWQ3NTgyMjY3YjUzZTJkZTlmZTY0NjQ2ZDQiLCJpYXQiOjE1ODI2MjE1NTUsIm5iZiI6MTU4MjYyMTU1NSwiZXhwIjoxNjE0MjQzOTU1LCJzdWIiOiIyIiwic2NvcGVzIjpbXX0.2oMpBrGj-ImwYG4klTIDxzauoo9-mNBSlG0QXo-d0SqrZv32v8LexVyCKJgKjtIkqbWk-7VMOU0k9sCccyII71td6P3emitBi2HvZoW115q81RHFF7SO5tG_Bk4cuju_vzzP2AEqntkSp9Aw_e2GSuDxffq2jYU5aJ-bqsWY6g5ljx1z4H48YYu4hHIUhhFquInaf8ix_ZIMvfqZUavkh-GpAJb-C5BGt97JBPYpSTOkGQxDVWkDIg9DsR6stCd0k4tjjVEHCdKEKf-MX1nIQHpSq7UiQhCDR5JdAStmW44zoOy2PqdYOhA4GHM4DNBZTxXgrGx4m2BGNc8Gi7MS5u15vfjyWcLZoPJ4elbQ279MTGj4V7-7EVqZ8i5KhJPqFWSIaHbQqeTaVtSvUp7j7YK2mzfaoIx4Q2EMuyqaxuEMViSpax8fAR4ezB1-2CUhursS0K4hxZGhVoQud954kdkZd04MLG5RY9PstCo1MtjFBD6p3emM_gcljug0mhzF7jEje9FezwBGgxJQ-1M6v-EZ7zS-Zgm3swPMv8sYKUacnsIJwjWQfTXaXtlD-kDMADs5VTlUuxuLzT7x9Baek1ZBYTza4djqW9MMK934EJ8gIOwg9tm1uOj6aPrfRSdlRMSPhxdc_5pLextbfgBquSpGLYRGMuUHOxrvUWH1ECo

###
