POST http://chat.lcl:8081/api/v1/chats
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiYzdhNzMyMDMwOGU2ZDgzMjk2NDU3ZmVlMTM1ODc0OTQwNzQyMzMyMzI2M2FmY2I3M2ViZjZlYzUwZDY4ODMwNTFhMTBkNTg2NDdmOTM0YTMiLCJpYXQiOjE1ODI2ODQ2NTYsIm5iZiI6MTU4MjY4NDY1NiwiZXhwIjoxNjE0MzA3MDU2LCJzdWIiOiIxIiwic2NvcGVzIjpbXX0.SttWgjntiCmEUzAwQnman137-YAyNqvSqumhuVseP6DtZkp25Y7qoeHO4ppeeP7GSRr8BBjxWq-1wR3twUOcijZo_cRkZ_If4TuHG1efmnGMzE6dUSoH08Qsygcsq8rCT73hsJ7mDk9IYGzXtIbrPCkxNL9RT10NtleNvm_wVNu7krxAaY6_kcQDXIZw-BtnjtvWBE1U583tfIrLgWo63nJJ7osxuHDQg_l8T__4wDZS0CrIzg_u47JOBipH0TB8c6aJMLMzTjW6bTvxwGsUJl0efhpzlnsU-nGPJu54xf1sB9107MuojAav3b9b8uU6O3D1CZN_doRkABWpkZMOti1i7VGpzJPAJW6jN4Z1DAWKjNXkKKrj_IFKpdRcAlH8mPIGIc_onEzTjvfPq2nA5iDSwk6wEBALf5RVlxcJdh3lsg51dvfubZ9lNi2pzlmBJVtmji1pzL4szY4oSuHCoOXw93VEOF6hXiVlkab0JYXwEoQlABleZsv_LFRJqPr8UWvrqNHvtktq_wTgttL2DwOhhzUMzbLuRGWcPX7FRDmdhruB4K6oCSADCE0r_3dVfBIG1XMgQhydPL8snaVDqDVsZ1yGcnUM4djxP96NzMWAfD4NdyL_Ls0eiC2Or7mQoj-XVUhfcK__1sZF3vPo6XLxlanwET-tKZniqHSSJbU

{
  "name": "test name"
}

###
