POST http://chat.lcl:8081/api/v1/register
Content-Type: application/json
Accept: application/json

{
  "name": "test",
  "email": "email@email.com",
  "password": "1q2w3e4r",
  "password_confirmation": "1q2w3e4r"
}

###

