POST http://chat.lcl:8081/api/v1/chats/23/messages
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiOTQzZDliNGVmMDFmM2QzMjVhZmRiNGIxZjUxODdlMjFiY2QwZTc0YmNkYjZlZGI0NWZkZjQ2ZDAzYmYxOTY3ODZhMGQ0MTUwYzM1NDE5ZDYiLCJpYXQiOjE1ODMxMTY1NjUsIm5iZiI6MTU4MzExNjU2NSwiZXhwIjoxNjE0NjUyNTY1LCJzdWIiOiIxIiwic2NvcGVzIjpbXX0.aQ1Z1uVJJSlQ3Av9xMEu6zlWWw8qvtJb5DS7-MBHYONc4VSZc0gubJZyHyYDdxbnW9LEqE0R8QA_m6gCHJYppXgxRVXKngw0HXIPFPOposl7iY_l3pKz2ILkoGacD0YJKuWnZmShRdLZu4B4L2GOVcS0YAoKgMHDqXjPr5C4-XNZEhJu_FVfTAVEQkFFWFu7dhJyxFmvDfsQTakhOUN9ua-ThGtYOefHwNWsq7fHn2xswOCJRdzMWls6kxYhFFMkL511_j85iX_Gbk_CSUoGQse4VUGE3uN6jqy-9E7281OM1Vqj51NxsybfnTZmTF3uHoZKbMAw23qvMxi7OS10dLKgq2398zv08dhBhTjV2yYEmfRk5bp8GwcWtVRbojTqy5gfbJ5Zd4DficA_mf7Ie4lHPoUen2d9_vZapfkaAW6H-gI-jnT0vkBO3JSKsZuYekzDObFdocGvCB-UtdKL7qBW33rCol2HxEGAATMN6wMYKoElQcBaB7WslSgbt2sNpB8NUMKMeBoE-9bHRAWlDuwtTBqeFodakrzTVw2Z9CCvvcUkVv6i1I1djNxtCMZhQOls83TLR6WE_E00XUz4foltClkeUwJWTMGRio0GwJYIIaMvRa-eTsLHRL9pwJFa3p0WbdcLzwj2wpgiJzf6952R_d2IezJcu7OhL0iH7iY

{
  "text": "Test message"
}

###
