DELETE http://chat.lcl:8081/api/v1/chats/2
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiYTg0ZjU4MjU1MmQxNDcxZTRiYjBmYzE4NDdmN2NhZDg1NmZkZTZkYjRmZDQ2YmU5ZTgyZGIzNDU2MGQwMWQ1OGQxOTcwMjAyY2JlZGJiZWIiLCJpYXQiOjE1ODI2ODk2MTUsIm5iZiI6MTU4MjY4OTYxNSwiZXhwIjoxNjE0MzEyMDE1LCJzdWIiOiIxIiwic2NvcGVzIjpbXX0.A88DWBMgjhI59cx0X4R-XM7fMLBhWIbNbNQW46ify-70uJFVODuiAHuUFbOmlRdZQwrxvcWfapGcPxu2Om3Oxa5BmC_RQgBPJkAEmi2SKqSU39NPo5MdHGwFJMngf2WaiQNZZAxyvzl6MCQ4vErlR3l5eZRspGDlA7vs9PQ0fl7K7MYg_z9ZwthIXSyDRL2_a-n-LUVfEu15lVbTgRypeU6_vQ2NtWNz-Pyx7CkOC_MSKoPy40l3H4XyquUSWDdve_L_IdP3nnTuaAorWa8rdA7QiuEQCVRQOReXPv-Xk9kwLg3z1k4TFJd_-HzjKAAiivv_2Eet2joCAnOG5_jo1q3Mh26voqxkSbmVAlG-gh_NXjXhY883rRUYaJGHjCf1NGKuNQCltsv9uvZ8zRG8kKB3OOvKd8n2_RM8X1hk3o7hHMXx7hdzp0B6Zjey4n77kpL4sFyp7raNPTzYXXyZYM6ewZbvoHhdKIbokvHLjsossIZX_qmqrB8Kjk1lBXZwbCvcbYd0SSyAfvH3gRIFW9FzPdG2RlRgjN0HBYJSAS0VZyUW1VYvYhhDzGHPeg6-zD_CrV3s8tW9wA66Dl4LjHm3X6iP_mREIJWYvPiLkzbOr5vbIkj451Mevl1VH8apqoadK_By0sYs_i_69P91nDlojCaY8Y_5CqdQxJFkQns

###
